# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d16bac8e81c6611d4061dfadfece009e2589145fcf59ce2b54847eb9f8a5b3aedf7d76ce748eb0306e3f196f4df21ea1487a4267f895ad9eccc01559c5e901d

test:
  secret_key_base: d9ef6b0b924e336ab944c4d8247afc275c0120ec3a657f6a42e308ed7a308558b4e74c0e9f1d04bb865b103502ddb03057e99086e5c7d3bfecbb7d9959a7f3d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
